name: Lint and Test

on:
  workflow_call:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Test
        run: bun test
